### PR TITLE
Serve Files 💅 

### PR DESCRIPTION
**Pull request by jpappel**
Created an nginx docker container that sits in front of the Flask webserver. Currently it there are no advantages to using it over the Flask http development server, but it will make it easier to implement https and hopefully less resource intensive to use S3 as per #12 .

Additionally, endpoints `/api/v1/file/<short_link>` and `/api/v1/file/<short_link>/info` to access files and a json containing some details. Boilerplate was written for various parts of the REST API that will need to get ironed out later.

API changes broke the tests which will be fixed after the demo of #5 for class November 20, 2023.

### CODE REVIEW

**Comment by jpappel** [comment]
I added some upload functionality and broke the existing tests 🥲 .

**Comment by drekdrek** [comment]
the problem is that theres no file called util.py with a function called get_mime_type
```py
 src/file_routes.py:3: in <module>
    from .util import get_mime_type
    ModuleNotFoundError: No module named 'src.util'
```
there is a built in class called mimetype and a function in it called guess_type

**Comment by jpappel** [comment]
It looks like I forgot to include `util.py` in my commit, oops. The reason the `get_mime_type` from `util.py` uses [Magic](https://pypi.org/project/python-magic/) to determine the mimetype from the file contents not just the filename. I choose this for security reasons. For example, if we wanted to block uploads of executeables we must check the file and not just trust the user.

If we revert back to using Magic to check mimetypes, we should verify libmagic is installed in the container. I believe it is installed by default in the python:3.10 image but adding a line in `flask/Dockerfile` would be best.

**Comment by drekdrek** [comment]
okay I see the reasoning behind using the magic library,
would you like to change it back to how you had it?

**Comment by jpappel** [comment]
Should be working as intended now

**Review by drekdrek — APPROVED** [review]
looks good

**Pull request merged**
